name: Build BrokeSMP Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Download Paper API
        run: |
          mkdir -p libs
          curl -L -o libs/paper-api.jar \
            https://api.papermc.io/v2/projects/paper/versions/1.21.8/builds/50/downloads/paper-1.21.8-50.jar

      - name: Compile plugin
        run: |
          mkdir -p build
          javac -cp "libs/paper-api.jar" -d build $(find src -name "*.java")

      - name: Copy resources (plugin.yml etc.)
        run: |
          mkdir -p build-resources
          cp plugin.yml build-resources/

      - name: Package plugin
        run: |
          jar cvf BrokeSMP.jar -C build . -C build-resources .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BrokeSMP
          path: BrokeSMP.jar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: BrokeSMP.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
