name: Build BrokeSMPV1

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: BrokeSMPV1
          path: target/*.jar
