name: Build BrokeSMPV1 (javac)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Download Paper API
        run: |
          mkdir -p libs
          curl -L -o libs/paper-api.jar \
            https://repo.papermc.io/repository/maven-public/io/papermc/paper/paper-api/1.21.8-R0.1-SNAPSHOT/paper-api-1.21.8-R0.1-SNAPSHOT.jar

      - name: Compile with javac
        run: |
          mkdir -p build/classes
          javac -cp libs/paper-api.jar -d build/classes $(find src/main/java -name "*.java")

      - name: Copy resources (plugin.yml etc.)
        run: |
          if [ -d src/main/resources ]; then
            cp -R src/main/resources/* build/classes/ || true
          fi

      - name: Package plugin jar
        run: |
          jar cf BrokeSMPV1.jar -C build/classes .

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: BrokeSMPV1
          path: BrokeSMPV1.jar
